name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: telus-koodo
  SERVICE_NAME: telusrecruitai
  REGION: asia-south1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t ${{ env.SERVICE_NAME }}:${{ github.sha }} .

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --port 3001 \
          --allow-unauthenticated \
          --set-env-vars="REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }},REACT_APP_NOTIFICATION_BASE_URL=${{ secrets.REACT_APP_NOTIFICATION_BASE_URL }},REACT_APP_AI_SEARCH_BASE_URL=${{ secrets.REACT_APP_AI_SEARCH_BASE_URL }}"
