name: Deploy to Cloud Run

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: telus-koodo
  SERVICE_NAME: telusrecruitai
  REGION: asia-south1
  REGISTRY: asia-south1-docker.pkg.dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Google Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Authorize Docker push
      run: |
        gcloud auth configure-docker ${{ env.REGISTRY }}

    - name: Build and Push Container
      run: |
        docker build -t ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE_NAME }} \
          --image ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --port 3001 \
          --allow-unauthenticated \
          --set-env-vars="REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }},REACT_APP_NOTIFICATION_BASE_URL=${{ secrets.REACT_APP_NOTIFICATION_BASE_URL }},REACT_APP_AI_SEARCH_BASE_URL=${{ secrets.REACT_APP_AI_SEARCH_BASE_URL }}"
